// mock-test-item.ts — 🧪 테스트 리뷰용 더미 ReviewItemWithChanges
import type { ReviewItemWithChanges } from '../shared/types';

export function createMockTestItem2(): ReviewItemWithChanges {
  return {
    id: 'test-cfg::github::888::7',
    gitConfigId: 'test-cfg',
    providerType: 'github',
    providerLabel: 'GH',
    itemId: 7,
    title: '[테스트2] fix: diff 뷰어 테이블 레이아웃 버그 수정',
    description: '탭 기능 테스트용 두 번째 PR입니다.',
    author: { id: 2, name: '김철수', username: 'chulsoo', avatar_url: '' },
    reviewers: [],
    viewerIsReviewer: false,
    webUrl: 'https://github.com/myorg/myrepo/pull/7',
    sourceBranch: 'fix/diff-table-layout',
    targetBranch: 'main',
    projectId: 888,
    repoFullName: 'myorg/myrepo',
    createdAt: new Date(Date.now() - 1_800_000).toISOString(),
    updatedAt: new Date().toISOString(),
    changes: [
      {
        old_path: 'src/renderer/shared/diff.css',
        new_path: 'src/renderer/shared/diff.css',
        new_file: false, deleted_file: false, renamed_file: false,
        diff: [
          "@@ -1,8 +1,18 @@",
          " .diff-table {",
          "   width: 100%;",
          "   border-collapse: collapse;",
          "-  table-layout: auto;",
          "+  table-layout: fixed;",
          " }",
          "+",
          "+.dc-col-gutter { width: 44px; }",
          "+.dc-col-code   { width: auto; }",
          "+",
          " .dc-gutter {",
          "-  width: 44px;",
          "-  min-width: 44px;",
          "   padding: 0 8px;",
          "   text-align: right;",
          "+  overflow: hidden;",
          " }",
        ].join('\n'),
      },
      {
        old_path: 'src/renderer/review/review-diff-modal.ts',
        new_path: 'src/renderer/review/review-diff-modal.ts',
        new_file: false, deleted_file: false, renamed_file: false,
        diff: [
          "@@ -30,6 +30,12 @@",
          "     <div class=\"modal-body diff-modal-body\">",
          "-      <table class=\"diff-table\">",
          "+      <table class=\"diff-table\" cellspacing=\"0\" cellpadding=\"0\">",
          "+        <colgroup>",
          "+          <col class=\"dc-col-gutter\">",
          "+          <col class=\"dc-col-gutter\">",
          "+          <col class=\"dc-col-code\">",
          "+        </colgroup>",
          "         <tbody id=\"diff-tbody\"></tbody>",
          "       </table>",
          "     </div>",
        ].join('\n'),
      },
      {
        old_path: 'src/renderer/review/review-tabs.ts',
        new_path: 'src/renderer/review/review-tabs.ts',
        new_file: true, deleted_file: false, renamed_file: false,
        diff: [
          "@@ -0,0 +1,20 @@",
          "+// review-tabs.ts — 탭 상태 관리",
          "+export interface ReviewTab {",
          "+  id: string;",
          "+  item: AnyItem;",
          "+  state: ReviewState;",
          "+  savedHtml: string;",
          "+  fileHtml: string;",
          "+  fileCount: string;",
          "+  errorMsg: string;",
          "+}",
          "+",
          "+export function addOrActivate(item: AnyItem): ReviewTab {",
          "+  const existing = tabs.find(t => t.id === item.id);",
          "+  if (existing) { activateById(existing.id); return existing; }",
          "+  const tab: ReviewTab = { id: item.id, item, state: 'idle',",
          "+    savedHtml: '', fileHtml: '', fileCount: '0', errorMsg: '' };",
          "+  tabs.push(tab);",
          "+  activateById(tab.id);",
          "+  return tab;",
          "+}",
        ].join('\n'),
      },
    ],
  };
}

export function createMockTestItem(): ReviewItemWithChanges {
  return {
    id: 'test-cfg::gitlab::999::42',
    gitConfigId: 'test-cfg',
    providerType: 'gitlab',
    providerLabel: 'GL',
    itemId: 42,
    title: '[테스트] feat: 펭귄 트레이 아이콘 + 다중 Git 연결 지원',
    description: '이것은 UI 테스트용 가짜 MR입니다.',
    author: { id: 1, name: '홍길동', username: 'gildong', avatar_url: '' },
    reviewers: [],
    viewerIsReviewer: false,
    webUrl: 'https://gitlab.example.com/mygroup/myrepo/-/merge_requests/42',
    sourceBranch: 'feat/penguin-tray',
    targetBranch: 'main',
    projectId: 999,
    createdAt: new Date(Date.now() - 3_600_000).toISOString(),
    updatedAt: new Date().toISOString(),
    changes: [
      {
        old_path: 'src/main/tray.ts',
        new_path: 'src/main/tray.ts',
        new_file: false, deleted_file: false, renamed_file: false,
        diff: [
          "@@ -1,8 +1,20 @@",
          "-import { Tray, Menu } from 'electron';",
          "+import { Tray, Menu, nativeImage } from 'electron';",
          "+import * as path from 'path';",
          " ",
          "-export function createTray(): void {",
          "-  // TODO",
          "+const ICON_FILES = {",
          "+  ACTIVE:  'icon-active.png',",
          "+  MUTED:   'icon-muted.png',",
          "+  NEW_MR:  'icon-new-mr.png',",
          "+  ERROR:   'icon-error.png',",
          "+};",
          "+",
          "+export function createTray(iconDir: string): Tray {",
          "+  const img = nativeImage.createFromPath(path.join(iconDir, ICON_FILES.ACTIVE));",
          "+  const tray = new Tray(img);",
          "+  tray.setToolTip('pingo');",
          "+  return tray;",
          " }",
        ].join('\n'),
      },
      {
        old_path: 'assets/icon-active.svg',
        new_path: 'assets/icon-active.svg',
        new_file: false, deleted_file: false, renamed_file: false,
        diff: [
          "@@ -1,5 +1,18 @@",
          "-<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"16\" height=\"16\"/>",
          "+<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 16 16\" width=\"16\" height=\"16\">",
          "+  <!-- 몸통 -->",
          "+  <ellipse cx=\"8\" cy=\"9\" rx=\"5\" ry=\"6\" fill=\"#1a1b2e\"/>",
          "+  <ellipse cx=\"8\" cy=\"9.5\" rx=\"3\" ry=\"4\" fill=\"#cdd6f4\"/>",
          "+  <!-- 눈 -->",
          "+  <circle cx=\"6.2\" cy=\"7\" r=\"1\" fill=\"white\"/>",
          "+  <circle cx=\"9.8\" cy=\"7\" r=\"1\" fill=\"white\"/>",
          "+  <circle cx=\"6.5\" cy=\"7.1\" r=\"0.5\" fill=\"#1a1b2e\"/>",
          "+  <circle cx=\"10.1\" cy=\"7.1\" r=\"0.5\" fill=\"#1a1b2e\"/>",
          "+  <!-- 부리 -->",
          "+  <ellipse cx=\"8\" cy=\"9\" rx=\"1.2\" ry=\"0.7\" fill=\"#f5c2e7\"/>",
          "+  <!-- 상태 점 -->",
          "+  <circle cx=\"13\" cy=\"12\" r=\"3\" fill=\"#a6e3a1\"/>",
          "+</svg>",
        ].join('\n'),
      },
      {
        old_path: 'src/renderer/review/review.css',
        new_path: 'src/renderer/review/review.css',
        new_file: false, deleted_file: false, renamed_file: false,
        diff: [
          "@@ -1,3 +1,15 @@",
          "+/* 탭 스트립 */",
          "+.review-tabstrip {",
          "+  display: flex;",
          "+  align-items: flex-end;",
          "+  height: 42px;",
          "+  padding: 0 var(--space-2) 0 var(--space-3);",
          "+  gap: 2px;",
          "+  background: var(--bg-base);",
          "+  border-bottom: 1px solid var(--border-subtle);",
          "+  -webkit-app-region: drag;",
          "+  overflow: hidden;",
          "+  flex-shrink: 0;",
          "+}",
          "+",
          " .review-root {",
        ].join('\n'),
      },
      {
        old_path: 'scripts/generate-icons.js',
        new_path: 'scripts/generate-icons.js',
        new_file: true, deleted_file: false, renamed_file: false,
        diff: [
          "@@ -0,0 +1,12 @@",
          "+const sharp = require('sharp');",
          "+const path = require('path');",
          "+const states = ['active', 'muted', 'new-mr', 'error'];",
          "+",
          "+async function main() {",
          "+  for (const s of states) {",
          "+    await sharp(`assets/icon-${s}.svg`)",
          "+      .resize(16, 16)",
          "+      .png()",
          "+      .toFile(`assets/icon-${s}.png`);",
          "+  }",
          "+}",
          "+main();",
        ].join('\n'),
      },
    ],
  };
}
